server:
  port: 8001
spring:
  application:
    name: alibaba-sentinel-datasource-nacos
  # sentinel dashboard
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  # sentinel datasource nacos ：http://blog.didispace.com/spring-cloud-alibaba-sentinel-2-1/
      datasource:
        ds:
          nacos: # 修改nacos的json文件，立即生效，但是修改sentinel不会生效（流控配置的时候失败）
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow

# 配置nacos
#[
#    {
#        "resource": "/api/sentinel/hello",
#        "limitApp": "default",
#        "grade": 1,
#        "count": 2,
#        "strategy": 0,
#        "controlBehavior": 0,
#        "clusterMode": false
#    }
#]
# resource：资源名，即限流规则的作用对象
# limitApp：流控针对的调用来源，若为 default 则不区分调用来源
# grade：限流阈值类型（QPS 或并发线程数）；0代表根据并发数量来限流，1代表根据QPS来进行流量控制
# count：限流阈值
# strategy：调用关系限流策略
# controlBehavior：流量控制效果（直接拒绝、Warm Up、匀速排队）
# clusterMode：是否为集群模式